version: 2.1
parameters:
  workingdir:
    type: string
    default: "~/app"
  node_version:
    type: string
    default: "12.16.1"
  docker_compose_version:
    type: string
    default: "1.25.3"

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:<< pipeline.parameters.node_version >>
    working_directory: << pipeline.parameters.workingdir >>
    steps:
      - checkout
      - run: |
          npm install
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/<< pipeline.parameters.docker_compose_version >>/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Create env file
          command: cp .env.example .env
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
  lint:
    docker:
      - image: circleci/node:<< pipeline.parameters.node_version >>
    working_directory: << pipeline.parameters.workingdir >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-
      - run: |
          npm run standard
  audit:
      docker:
        - image: circleci/node:<< pipeline.parameters.node_version >>
      working_directory: << pipeline.parameters.workingdir >>
      steps:
        - checkout
        - restore_cache:
            keys:
              - dependencies-{{ checksum "package-lock.json" }}
              - dependencies-
        - run: |
            npm audit
  tests:
      machine: true
      working_directory: << pipeline.parameters.workingdir >>
      steps:
        - checkout
        - restore_cache:
            keys:
              - dependencies-{{ checksum "package-lock.json" }}
              - dependencies-
        - run:
            name: Run tests
            command: make test
        - attach_workspace:
            at: << pipeline.parameters.workingdir >>
        - store_artifacts:
            path: << pipeline.parameters.workingdir >>/junit.xml
        - store_test_results:
            path: << pipeline.parameters.workingdir >>/junit.xml
        - persist_to_workspace:
            root: << pipeline.parameters.workingdir >>
            paths:
              - ./
  sonar_pull_request:
      machine: true
      working_directory: << pipeline.parameters.workingdir >>
      steps:
        - checkout
        - restore_cache:
            keys:
              - dependencies-{{ checksum "package-lock.json" }}
              - dependencies-
        - attach_workspace:
            at: << pipeline.parameters.workingdir >>
        - run:
            name: Edit propertie file
            command: |
              echo "sonar.pullrequest.branch=${CIRCLE_BRANCH}" >> sonar-project.properties
              echo "sonar.pullrequest.key=${CIRCLE_PULL_REQUEST//[!0-9]/}" >> sonar-project.properties
              echo "sonar.pullrequest.base=master" >> sonar-project.properties
        - sonarcloud/scan
  sonar_master:
      machine: true
      working_directory: << pipeline.parameters.workingdir >>
      steps:
        - checkout
        - restore_cache:
            keys:
              - dependencies-{{ checksum "package-lock.json" }}
              - dependencies-
        - attach_workspace:
            at: << pipeline.parameters.workingdir >>
        - run:
            name: Edit propertie file
            command: echo "sonar.branch.name=${CIRCLE_BRANCH}" >> sonar-project.properties
        - sonarcloud/scan
     
workflows:
    build-and-test:
      jobs:
        - build

        - lint:
            requires:
              - build

        - audit:
            requires:
              - build

        - tests:
            requires:
              - audit
              - lint
            context: sonarcloud

        - sonar_pull_request:
            requires:
              - tests
            context: sonarcloud
            filters:
              branches:
                ignore:
                  - master

        - sonar_master:
            requires:
              - tests
            context: sonarcloud
            filters:
              branches:
                only: master
